spring:
  application:
    name: backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/main_changelog.xml
  docker:
    compose:
      file: backend/deploy/docker-compose.yaml
      profiles:
        active: develop
      lifecycle-management: start_only
      start:
        command: up
      stop:
        command: down
        timeout: 0
      enabled: true
server:
  port: 8080
